---
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
    volumes:
      - ${PLEX_LIBRARY_PATH}:/config
      - ${PLEX_TV_PATH}:/tv
      - ${PLEX_MOVIES_PATH}:/movies
    restart: unless-stopped
